name: black-jack
channels:
  - pytorch
  - conda-forge
  - pypi
  - conda
dependencies:
  - coverage == 7.5.*
  - ipykernel == 6.29.*
  - ipython == 8.22.*
  - keyboard == 0.13.*
  - markdown == 3.4.*
  - matplotlib == 3.8.*
  - numpy == 1.25.*
  - pandas == 2.2.*
  - polars == 0.20.*
  - pytorch == 2.2.*
  - pytorch-lightning == 2.2.*
  - scikit-learn == 1.4.*
  - scipy == 1.11.*
  - tqdm == 4.64.*
  - pip == 24.0.*